### ISSUE TITLE
Version NPM

### ISSUE THREAD

**Issue by fega** [montalvomiguelo/platziprofile#3]
Por si curiosidad te da :)
https://github.com/fega/platzi-profile

**Comment by montalvomiguelo** [comment]
Woot esta buenísimo dude 👍 mi scrapper se murió cuando rediseñaron la pagina de profiles xD... usaré el tuyo para actualizar el mío :-)

Inicialmente creo que lo utilizaba para hacer un plugin de WordPress y poder mostrar mis badges en mi blog personal _(después lo cambie a jekyll)_ .

También ese plugin puede revivir ahora xD https://github.com/montalvomiguelo/Platzi-Badges-Plugin

**Comment by fega** [comment]
jajajaja, yo lo utilizare para mi pagina web personal hecha Vue.js
Si necesitas la version microservicio: 
https://github.com/fega/platzi-profile-web 
https://platzi-profile.herokuapp.com/

**Comment by montalvomiguelo** [comment]
![](https://cloud.githubusercontent.com/assets/5587545/6083283/ffd153be-adec-11e4-89b8-4dad4a08dcfd.gif)
